name: golangci-lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  golangci:
    strategy:
      matrix:
        go-version: ["1.15", "1.14", "1.13"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
